version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Black
          command: |
            . venv/bin/activate
            black --check .
      - run:
          name: Run isort
          command: |
            . venv/bin/activate
            isort --check-only .
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            flake8

workflows:
  version: 2
  linting-workflow:
    jobs:
      - lint
